### ISSUE TITLE
why   import color although you didn't use it ?

### ISSUE THREAD

**Issue by AbanoubAshraaf** [xxsiders/UITEMPLATE#1]
https://github.com/xxsiders/UITEMPLATE/blob/4bc2d8904ab37f108e89ed803837659664abbcda/src/utilities/MainLoader.js#L3

**Comment by AbanoubAshraaf** [comment]
isuue

**Comment by xxsiders** [comment]
> https://github.com/xxsiders/UITEMPLATE/blob/4bc2d8904ab37f108e89ed803837659664abbcda/src/utilities/MainLoader.js#L5
